// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtBlVPIpUpAshS9e4xqQRJ3iJXpzNA1Ns',
    appId: '1:216098069245:android:cb741b7bfde32cb5877c94',
    messagingSenderId: '216098069245',
    projectId: 'medtech-2d328',
    storageBucket: 'medtech-2d328.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC4podd37QvvaOiZpy2x9E9rrZ0ZX-hTY',
    appId: '1:216098069245:ios:66b0a5739487d284877c94',
    messagingSenderId: '216098069245',
    projectId: 'medtech-2d328',
    storageBucket: 'medtech-2d328.appspot.com',
    androidClientId: '216098069245-3lpeauu7sn3ge99iu742tc7vchkor0io.apps.googleusercontent.com',
    iosClientId: '216098069245-jq87umrgk7s5sc5uemmn1q5c9j1old49.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdetech.medtech',
  );
}
